language: node_js
branches:
  except:
    - design
notifications:
  email: false
node_js:
  - 0.8
  - 0.10
services: mongodb
before_install:
  - gem update --system
  - gem install compass
  - npm install -g grunt-cli
